### ISSUE TITLE
I don't need null, I need undefined!

### ISSUE THREAD

**Issue by justusromijn** [mickael-kerjean/just-a-joke#2]
This is probably better suited as a feature request: I would like to be able to alternate between null and undefined, are there plans to extend this package to support undefined as well? Thanks in advance!

**Comment by neroux** [comment]
I am not quite sure what to think of that, I am afraid. On one hand _nulll_ is an opinionated framework for a reason and we should not dismiss the intrinsic value of this. On the other hand though, an exaggerated customisability has always been a fantastic idea and I do believe _nulll_ could do with a vast array of configuration options via dependency injection.

It's a tough call.

**Comment by shaunburdick** [comment]
@justusromijn  Until they respond to your completely reasonable request, the obvious answer is to split the library and publish a [new one](https://github.com/shaunburdick/undefinedd).

**Comment by justusromijn** [comment]
Thanks, I guess I will need to include them both in my project for the time being. What I really need is one huge package that fixes all my problems that I have now, ever will, or never will have. I will continue my search for this silver bullet.
